export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_USER = 'FETCH_USER';

export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL';

export const COMPLETE_SUBSCRIPTION = 'COMPLETE_SUBSCRIPTION';
export const WAIT_SUBSCRIPTION = 'WAIT_SUBSCRIPTION';
export const REPORT_ERROR_SUBSCRIPTION = 'REPORT_ERROR_SUBSCRIPTION';
export const NOT_SUBSCRIBED = 'NOT_SUBSCRIBED';
